version: '3.9'
services:
  proxyxai-openai:
    container_name: proxyxai-openai
    image: proxyxai/openai
    pull_policy: always
    restart: always
    depends_on:
      proxyxai-redis:
        condition: service_started
      proxyxai-postgres:
        condition: service_healthy
    ports:
      - 3443:3443
    environment:
      - SINGLE_MODE=true
      - TZ=Asia/Shanghai
      - PORT=3443
      - POSTGRES_DSN=user=postgres password=pass host=proxyxai-postgres dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai
      - REDIS_ADDR=proxyxai-redis:6379
      - REDIS_PASS=
        # 100次请求/账号,数据落盘Redis,100*10次请求/账号,数据落盘PostgreSQL
      - STATS_INTERVAL=100
        # 必选设置 初始root用户;格式 root:邮箱地址:管理Key;请注意管理Key为51个字符,开头必须是 sk-Xvs, 初始用户名必须是 root
      - INIT_USERS=root:root@proxyxai.com:sk-XvsiLNxHImLIn0chuNDdi5wTs5WaoEWNcd87Z62etZZ1bz7z
        # 必选设置 OpenAI API 接入点
      - OPENAI_API_BASE=api.openai.com
        # 可选设置 启动即刻录入OpenAI API Keys(也可以启动后,通过管理 API 操作录入),如果 OPENAI_API_BASE 不是 api.openai.com,则需要录入自定义节点的 Keys;格式 sk-xxx,sk-xxx,sk-xxx
      - INIT_KEYS=
        # 新建账号初始充值需要的最小额度
      - USER_MIN_BALANCE=2.00
        # 开通子账号管理权限需要的最小额度
      - USER_API_MIN_BALANCE=20.00
        # 可选设置 一级域名,请改成自己的主域名,仅作为系统邮件模版页脚显示
      - XAI_SERVICE=proxyxai.com
        # 可选设置 邮件服务
      - EMAIL_SMTP=smtp.gmail.com
      - EMAIL_PORT=465
      - EMAIL_AUTH=
      - EMAIL_PASS=
      - EMAIL_SENDER=
      - EMAIL_TLS=true
    networks:
      - proxyxai-openai-network
  proxyxai-postgres:
    container_name: proxyxai-postgres
    image: postgres:16
    pull_policy: always
    restart: always
    user: postgres
    environment:
      TZ: "Asia/Shanghai"
      PGTZ: "Asia/Shanghai"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "postgres"
        ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - proxyxai-openai-network
  proxyxai-redis:
    container_name: proxyxai-redis
    image: redis:alpine
    pull_policy: always
    restart: always
    volumes:
      - redis_data:/data
    environment:
      - TZ=Asia/Shanghai
    networks:
      - proxyxai-openai-network
volumes:
  redis_data:
  postgres_data:
networks:
  proxyxai-openai-network:
    driver: bridge
